### PR TITLE
Feat: Add watchlater

### PR DESCRIPTION
**Pull request by starver20**
Added watchlater functionalities

### CODE REVIEW

**Comment by AnkurChunekar** [comment]
Hey @starver20 , 
Even if I am logged in, when I try to add a video to watch later, I am redirected to the same login page please look into this.

**Comment by starver20** [comment]
> Hey @starver20 , Even if I am logged in, when I try to add a video to watch later, I am redirected to the same login page please look into this.

Fixed it. Thanks.

**Comment by AnkurChunekar** [comment]
amar pr

This isn't really a bug but some of the videos in watch later have image greater than the others, which looks inconsistent

**Review by AnkurChunekar — APPROVED** [review]

**Review by kart-c — APPROVED** [review]
Great comments @starver20 really helped me understand your code more easily. Also great job on the watch later controller 👍

**Comment by starver20** [comment]
> amar pr
> 
> This isn't really a bug but some of the videos in watch later have image greater than the others, which looks inconsistent

Thanks, fixed it.

**Comment by starver20** [comment]
> Great comments @starver20 really helped me understand your code more easily. Also great job on the watch later controller +1

Thank you.

**Pull request merged**
